spring:
  datasource:
#    url: jdbc:mysql://192.168.0.143/base_project?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: jiang101
#    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:mysql://140.210.16.43/dsrs?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: Super000#
#    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://140.210.16.15/security_mgmt_zj?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Super000#
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 9800

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.demo.mapper: debug


name: "zhangsan"